# Jido framework macro-generated code issues
# All errors below are false positives from the Jido.Agent and Jido.Action macros
# Use Path.expand for deps to work in both CI and local environments

[
  # Unused functions - these ARE used but Dialyzer can't trace through macro expansion
  {Path.expand("deps/jido/lib/jido/agent.ex"), :unused_fun},

  # Contract violations - macro-generated specs don't match Dialyzer's inference
  {Path.expand("deps/jido/lib/jido/agent.ex"), :call},

  # Invalid contracts in our agent modules - generated by `use Jido.Agent` macro
  {"lib/labs_jido_agent/code_review_agent.ex", :invalid_contract},
  {"lib/labs_jido_agent/progress_coach_agent.ex", :invalid_contract},
  {"lib/labs_jido_agent/study_buddy_agent.ex", :invalid_contract},

  # Pattern match issue in progress coach action - macro-generated validation code
  {"lib/labs_jido_agent/progress_coach_action.ex", :pattern_match}
]
